name: linux
on: [push]
jobs:
  bazel-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install libudev-dev
        run: sudo apt-get install -y libudev-dev
      - name: Build and test all targets
        run: bazelisk test //...
